include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - cancel_subscriptions
    - close_sinks
    - no_adjacent_strings_in_list
    - unnecessary_statements
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_js_rounded_ints
    - avoid_positional_boolean_parameters
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - flutter_style_todos
    - lines_longer_than_80_chars
    - missing_whitespace_between_adjacent_strings
    - no_runtimeType_toString
    - omit_local_variable_types
    - only_throw_errors
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_constructors_over_static_methods
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_interpolation_to_compose_strings
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - use_is_even_rather_than_modulo
    - use_setters_to_change_properties
    - sort_pub_dependencies

analyzer:
  plugins:
    - dart_code_metrics
  errors:
    invalid_annotation_target: ignore

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 5
    source-lines-of-code: 50
    weight-of-class: 0.33
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return:
        severity: style
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma:
        severity: style
    - prefer-conditional-expressions
    - no-equal-then-else

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options